# Site settings
title: Jakub Slaby
email: kubo.slaby[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Jakub Slaby, a front-end developer originally from Slovakia, currently living and working for <a href='http://phantom.land'>Phantom</a> in London.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jakubslaby.net" # the base hostname & protocol for your site
twitter_username: jakubsl
github_username:  jakubsl
linkedin_username: slabyjakub

#Sitemap generation
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# Permalink structure for blog posts
permalink: /blog/:title/
